### ISSUE TITLE
Lift Subsystem

### ISSUE THREAD

**Issue by baileypf** [The-Charge/2015_TrashBot#14]
What is with the calling of the break???

**Comment by AmandaKline** [comment]
![image](https://cloud.githubusercontent.com/assets/9940584/6312352/5bb90f58-b943-11e4-9821-73b41de8a1f0.jpg)

**Comment by bammerman** [comment]
Remove brake from initialize command and leave it in the subsystem

**Comment by abcurrie** [comment]
done
