### ISSUE TITLE
Button Box - Lift Speed

### ISSUE THREAD

**Issue by bammerman** [The-Charge/2015_TrashBot#20]
Read POTS and that would change the lift speed for fast and slow respectively.

**Comment by abcurrie** [comment]
Fast   .7 - 1.0       Slow   .3  -  .7  with .4 in the middle

**Comment by AmandaKline** [comment]
Commited and pushed in branch AnalogInputs

**Comment by AmandaKline** [comment]
Needs to be tested but looks good. :smile:
