### ISSUE TITLE
Add labels to issues 

### ISSUE THREAD

**Issue by Shalmezad** [The-Charge/2015_TrashBot#22]
Bailey:
Not sure if you noticed, but github has the ability to add labels to issues. I went through and added a few and tagged some.

Make sure that as programmers finish, they add the "ready to merge" label to the issue so we know it's ready to go into develop.

Also, any additional labels that you see fit should be added (such as the "help wanted" label on this issue, noting that it requires someone else's attention). 

See this for details on creating/modifying them:
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by Shalmezad** [comment]
Also, need to decide which issues are the highest priority and need to be done first.

**Comment by AmandaKline** [comment]
Hey Shalmezad (why is this your name I can't spell it) Baily's not here today and we were all confused as to what the lables were till we found this it's me and Brittany right now. :two_women_holding_hands: :tada: :computer:
