### ISSUE TITLE
StrafeXFeet

### ISSUE THREAD

**Issue by baileypf** [The-Charge/2015_TrashBot#6]
Constants need to be changed for TrashBot in StrafeXFeet and DriveXFeet.

**Comment by AmandaKline** [comment]
Need Tuning constants to change feet->ticks, and they need to be on the smart dashboard. Right now use the approximate calculations in the code right now, but make them accessable to the SD.

**Comment by AmandaKline** [comment]
Made TICKS_PER_1_FOOT_STRAFE manipulable from the SD. Branch: StrafeXFeetConstants.

**Comment by AmandaKline** [comment]
Also edited the constant for DriveXFeet, making TICKS_PER_ONE_FOOT and sending it to the SD.
